apiVersion: v1
kind: Service
metadata:
  name: qashqade-service
  namespace: default
spec:
  selector:
    app: qashqade-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4004
  type: ClusterIP